project:
  type: website
  render:
  - "*.qmd"
  - "!internal/"

website:
  title: "Shiny en una sentada"
  repo-url: https://github.com/CentroGeo/tutorial-shiny-cig2022
  repo-actions: [issue]
  navbar:
    logo: "cgeo_logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Acerca
    right:
      - icon: github
        href: https://github.com/CentroGeo/tutorial-shiny-cig2022
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/CentroGeo_
        aria-label: Twitter
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Graficas"
        contents:
          - serie_tiempo.qmd
          - scatter_plot.qmd
          - mapa.qmd
      - section: "Aplicación"
        contents:
          - intro_shiny.qmd
          - text: "Mi primera aplicación"
            href: https://plablo.shinyapps.io/mi-primer-app-CIG-2022/
          - integrando.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



