project:
  type: website
  render:
  - "*.qmd"
  - "!internal/"

website:
  title: "Tutorial Shiny"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Acerca
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Graficas"
        contents:
          - serie_tiempo.qmd
          - scatter_plot.qmd
          - mapa.qmd
      - section: "Aplicación"
        contents:
          - intro_shiny.qmd
          - text: "Mi primera aplicación"
            href: https://plablo.shinyapps.io/mi-primer-app-CIG-2022/
          - integrando.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



