project:
  type: website

website:
  title: "Tutorial Shiny"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Acerca
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Graficas"
        contents:
          - scatter.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



